version: '3.7'

services:

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/images/app/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
      - ./docker/conf/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/conf/crontab:/etc/crontabs/root
      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/php-fpm.ini:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /app

  nginx:
    image: nginx
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/conf/crontab:/etc/crontabs/root
      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/php-fpm.ini:/usr/local/etc/php-fpm.d/www.conf

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: 'test_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  dump:
  postgresql:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
