# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /swagger/swagger.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /swagger/
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui}
